CREATE TABLE [Staging].[AeProviders] (
    [AeProviderId] INT IDENTITY (1, 1) NOT NULL,
    [AeServiceProviderIdentifierSea]            NVARCHAR (50)   NULL,
    [NameOfInstitution]                         NVARCHAR (1000) NULL,
    [ShortNameOfInstitution]                    NVARCHAR (30)   NULL,
    [AdultEducationProviderTypeCode]            NVARCHAR (50)   NULL,
    [AdultEducationProviderTypeDescription]     NVARCHAR (150)  NULL,
    [LevelOfInstitutionCode]                    NVARCHAR (50)   NULL,
    [LevelOfInstitutionDescription]             NVARCHAR (150)  NULL,
    [TelephoneNumber]                           NVARCHAR (24)   NULL,
    [FaxNumber]                                 NVARCHAR (20)   NULL,
	[Email]                                     NVARCHAR (100)   NULL,
    [WebSiteAddress]                            NVARCHAR (300)  NULL,
    [MailingAddressStreetNumberAndName]         NVARCHAR (150)  NULL,
    [MailingAddressApartmentRoomOrSuiteNumber]  NVARCHAR (60)   NULL,
    [MailingAddressCity]                        NVARCHAR (30)   NULL,
    [MailingAddressStateAbbreviation]           NVARCHAR (50)   NULL,
    [MailingAddressPostalCode]                  NVARCHAR (17)   NULL,
    [MailingAddressCountyAnsiCodeCode]          NVARCHAR (50)   NULL,
    [PhysicalAddressStreetNumberAndName]        NVARCHAR (150)  NULL,
    [PhysicalAddressApartmentRoomOrSuiteNumber] NVARCHAR (60)   NULL,
    [PhysicalAddressCity]                       NVARCHAR (30)   NULL,
    [PhysicalAddressStateAbbreviation]          NVARCHAR (50)   NULL,
    [PhysicalAddressPostalCode]                 NVARCHAR (17)   NULL,
    [PhysicalAddressCountyAnsiCodeCode]         NVARCHAR (50)   NULL,
    [LocationID]                                INT             NULL,
	[VenID]                                     NVARCHAR (11)   NULL,
	[OrgStartDate]                              DATETIME        NULL,
	[OrgStopDate]                               DATETIME        NULL,
    [Latitude]                                  NVARCHAR (20)   NULL,
    [Longitude]                                 NVARCHAR (20)   NULL,
    [OrgType]                                   NVARCHAR (20)   NULL,
    [RecordStartDateTime]                       DATETIME        NULL,
    [RecordEndDateTime]                         DATETIME        NULL,
    [RunDateTime]                               DATETIME        NULL,
    [SchoolYear]                                SMALLINT        NULL,
    [HashValue]                                 binary	(32)    NULL,
    CONSTRAINT [PK_AeProviders] PRIMARY KEY CLUSTERED ([AeProviderId] ASC)
);

GO