CREATE TABLE [Staging].[AssessmentResult] (
    [Id]                                             INT           IDENTITY (1, 1) NOT NULL,
    [StudentIdentifierState]                         NVARCHAR (40) NULL,
    [LeaIdentifierSeaAccountability]                 NVARCHAR (50) NULL,
    [LeaIdentifierSeaAttendance]                     NVARCHAR (50) NULL,
    [LeaIdentifierSeaFunding]                        NVARCHAR (50) NULL,
    [LeaIdentifierSeaGraduation]                     NVARCHAR (50) NULL,
    [LeaIdentifierSeaIndividualizedEducationProgram] NVARCHAR (50) NULL,
    [SchoolIdentifierSea]                            VARCHAR (50)  NULL,
    [AssessmentTitle]                                VARCHAR (100) NULL,
    [AssessmentAcademicSubject]                      VARCHAR (100) NULL,
    [AssessmentPurpose]                              VARCHAR (100) NULL,
    [AssessmentType]                                 VARCHAR (100) NULL,
    [AssessmentTypeAdministered]                     VARCHAR (100) NULL,
    [AssessmentTypeAdministeredToEnglishLearners]    VARCHAR (100) NULL,
    [AssessmentAdministrationStartDate]              DATE          NULL,
    [AssessmentAdministrationFinishDate]             DATE          NULL,
    [AssessmentRegistrationParticipationIndicator]   BIT           NULL,
    [GradeLevelWhenAssessed]                         VARCHAR (100) NULL,
    [ScoreValue]                                     VARCHAR (50)  NULL,
    [StateFullAcademicYear]                          VARCHAR (100) NULL,
    [LEAFullAcademicYear]                            VARCHAR (100) NULL,
    [SchoolFullAcademicYear]                         VARCHAR (100) NULL,
    [AssessmentRegistrationReasonNotCompleting]      VARCHAR (100) NULL,
    [AssessmentPerformanceLevelIdentifier]           VARCHAR (100) NULL,
    [AssessmentPerformanceLevelLabel]                VARCHAR (100) NULL,
    [AssessmentScoreMetricType]                      VARCHAR (100) NULL,
    [SchoolYear]                                     SMALLINT      NULL,
    [DataCollectionName]                             VARCHAR (100) NULL,
    [DataCollectionId]                               INT           NULL,
    [AssessmentRegistrationId]                       INT           NULL,
    [AssessmentAdministrationId]                     INT           NULL,
    [AssessmentId]                                   INT           NULL,
    [PersonId]                                       INT           NULL,
    [AssessmentFormId]                               INT           NULL,
    [AssessmentSubtestId]                            INT           NULL,
    [AssessmentPerformanceLevelId]                   INT           NULL,
    [AssessmentResultId]                             INT           NULL,
    [AssessmentResult_PerformanceLevelId]            INT           NULL,
    [OrganizationID_LEA]                             INT           NULL,
    [OrganizationPersonRoleId_LEA]                   INT           NULL,
    [OrganizationID_School]                          INT           NULL,
    [OrganizationPersonRoleId_School]                INT           NULL,
    [RunDateTime]                                    DATETIME      NULL,
    CONSTRAINT [PK_AssessmentResult] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, DATA_COMPRESSION = PAGE)
);


GO

