CREATE TABLE [Staging].[CredentialDefinition]
(
  [Id]                                                          INT NOT NULL IDENTITY(1,1),
  [CredentialDefinitionIdentifierCtid]                          [nvarchar](512) NULL,
  [CredentialDefinitionTitle]                                   [nvarchar](300) NULL,
  [CredentialDefinitionDescription]                             [nvarchar](300) NULL,
  [CredentialTypeCode]                                          [nvarchar](50) NULL,
  [CredentialTypeDescription]                                   [nvarchar](200) NULL,
  [CredentialDefinitionCategorySystem]                          [nvarchar](30) NULL,
  [CredentialDefinitionCategoryType]                            [nvarchar](60) NULL,
  [CredentialDefinitionStatusTypeCode]                          [nvarchar](50) NULL,
  [CredentialDefinitionStatusTypeDescription]                   [nvarchar](200) NULL,
  [CredentialDefinitionIntendedPurposeTypeCode]                 [nvarchar](50) NULL,
  [CredentialDefinitionIntendedPurposeTypeDescription]          [nvarchar](200) NULL,
  [CredentialDefinitionAssessmentMethodTypeCode]                [nvarchar](50) NULL,
  [CredentialDefinitionAssessmentMethodTypeDescription]         [nvarchar](200) NULL,
  [CredentialDefinitionCriteria]                                [nvarchar](300) NULL,
  [CredentialDefinitionCriteriaURL]                             [nvarchar](512) NULL,
  [CredentialDefinitionKeywords]                                [nvarchar](max) NULL,
  [CredentialDefinitionValidationMethodDescription]             [nvarchar](max) NULL,
  [CredentialImageURL]                                          [nvarchar](512) NULL,
  [CredentialDefinitionDateEffective]                           [date] NULL,
  [CTDLAudienceLevelTypeCode]                                   [nvarchar](50) NULL,
  [CTDLAudienceLevelTypeDescription]                            [nvarchar](200) NULL,
  [CredentialDefinitionTerminalDegreeIndicatorCode]             [nvarchar](50) NULL,
  [CredentialDefinitionTerminalDegreeIndicatorDescription]      [nvarchar](200) NULL,
  [CredentialDefinitionScedCode]                                [nvarchar](50) NULL,
  [CredentialDefinitionLowGradeLevelCode]                       [nvarchar](50) NULL,
  [CredentialDefinitionHighGradeLevelCode]                      [nvarchar](50) NULL,
)
