CREATE TABLE [Staging].[Discipline] (
    [Id]                                             INT            IDENTITY (1, 1) NOT NULL,
    [SchoolYear]                                     SMALLINT       NULL,
    [StudentIdentifierState]                         NVARCHAR (40)  NULL,
    [LeaIdentifierSeaAccountability]                 NVARCHAR (50)  NULL,
    [LeaIdentifierSeaAttendance]                     NVARCHAR (50)  NULL,
    [LeaIdentifierSeaFunding]                        NVARCHAR (50)  NULL,
    [LeaIdentifierSeaGraduation]                     NVARCHAR (50)  NULL,
    [LeaIdentifierSeaIndividualizedEducationProgram] NVARCHAR (50)  NULL,
    [SchoolIdentifierSea]                            NVARCHAR (50)  NULL,
    [DisciplineActionIdentifier]                     NVARCHAR (100) NULL,
    [IncidentIdentifier]                             NVARCHAR (40)  NULL,
    [IncidentDate]                                   DATE           NULL,
    [IncidentTime]                                   TIME (7)       NULL,
    [DisciplinaryActionTaken]                        NVARCHAR (100) NULL,
    [DisciplineReason]                               NVARCHAR (100) NULL,
    [DisciplinaryActionStartDate]                    NVARCHAR (100) NULL,
    [DisciplinaryActionEndDate]                      NVARCHAR (100) NULL,
    [IncidentInjuryType]                             NVARCHAR (100) NULL,
    [IncidentBehavior]                               NVARCHAR (100) NULL,
    [DurationOfDisciplinaryAction]                   NVARCHAR (100) NULL,
    [IdeaInterimRemoval]                             NVARCHAR (100) NULL,
    [IdeaInterimRemovalReason]                       NVARCHAR (100) NULL,
    [EducationalServicesAfterRemoval]                BIT            NULL,
    [DisciplineMethodFirearm]                        NVARCHAR (100) NULL,
    [IDEADisciplineMethodFirearm]                    NVARCHAR (100) NULL,
    [DisciplineMethodOfCwd]                          NVARCHAR (100) NULL,
    [WeaponType]                                     NVARCHAR (100) NULL,
    [FirearmType]                                    NVARCHAR (100) NULL,
    [DataCollectionName]                             NVARCHAR (100) NULL,
    [PersonId]                                       INT            NULL,
    [OrganizationID_LEA]                             INT            NULL,
    [OrganizationPersonRoleId_LEA]                   INT            NULL,
    [OrganizationID_School]                          INT            NULL,
    [OrganizationPersonRoleId_School]                INT            NULL,
    [IncidentId_LEA]                                 INT            NULL,
    [IncidentId_School]                              INT            NULL,
    [RunDateTime]                                    DATETIME       NULL,
    CONSTRAINT [PK_Discipline] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, DATA_COMPRESSION = PAGE)
);


GO

