CREATE TABLE [Staging].[Employers]
(
  [Id]                                                            [int] IDENTITY(1,1) NOT NULL,
	[EmployerOrganizationName]                                      [nvarchar](1000) NULL,
	[EmployerOrganizationIdentifierSea]                             [nvarchar](50) NULL,
	[SeaOrganizationName]                                           [nvarchar](1000) NULL,
	[SeaOrganizationIdentifierSea]                                  [nvarchar](50) NULL,
	[StateANSICode]                                                 [nvarchar](10) NULL,
	[StateAbbreviationCode]                                         [nvarchar](10) NULL,
	[StateAbbreviationDescription]                                  [nvarchar](1000) NULL,
	[MailingAddressStreetNumberAndName]                             [nvarchar](150) NULL,
	[MailingAddressApartmentRoomOrSuiteNumber]                      [varchar](40) NULL,
	[MailingAddressCity]                                            [nvarchar](30) NULL,
	[MailingAddressStateAbbreviation]                               [nvarchar](50) NULL,
	[MailingAddressPostalCode]                                      [nvarchar](17) NULL,
	[MailingAddressCountyAnsiCodeCode]                              [char](5) NULL,
	[OutOfStateIndicator]                                           [bit] NOT NULL,
	[OrganizationOperationalStatus]                                 [varchar](20) NULL,
	[OperationalStatusEffectiveDate]                                [datetime] NULL,
	[PhysicalAddressStreetNumberAndName]                            [nvarchar](150) NULL,
	[PhysicalAddressApartmentRoomOrSuiteNumber]                     [varchar](40) NULL,
	[PhysicalAddressCity]                                           [nvarchar](30) NULL,
	[PhysicalAddressPostalCode]                                     [nvarchar](17) NULL,
	[PhysicalAddressStateAbbreviation]                              [nvarchar](50) NULL,
	[PhysicalAddressCountyAnsiCodeCode]                             [char](5) NULL,
	[TelephoneNumber]                                               [nvarchar](24) NULL,
	[WebSiteAddress]                                                [nvarchar](300) NULL,
	[OrganizationRegionGeoJson]                                     [nvarchar](max) NULL,
	[Latitude]                                                      [nvarchar](20) NULL,
	[Longitude]                                                     [nvarchar](20) NULL,
	[RecordStartDateTime]                                           [datetime] NOT NULL,
	[RecordEndDateTime]                                             [datetime] NULL
)