CREATE TABLE Staging.K12FinancialAccountGeneralLedger (
	  Id																INT IDENTITY (1, 1) NOT NULL
	, SeaOrganizationIdentifierSea										NVARCHAR(60) NULL
	, IeuOrganizationIdentifierSea										NVARCHAR(60) NULL
	, LeaIdentifierSea													NVARCHAR(60) NULL
	, SchoolIdentifierSea												NVARCHAR(60) NULL
	, FiscalAccountingDate												DATE NULL
	, FiscalYear														SMALLINT NULL
	, FiscalPeriodBeginDate									DATE NULL
	, FiscalPeriodEndDate									DATE NULL
	, Federal_FinancialAccountBalanceSheetCodeCode						NVARCHAR(50) NULL
	, Sea_FinancialAccountLocalBalanceSheetCodeCode						NVARCHAR(50) NULL
	, Lea_FinancialAccountLocalBalanceSheetCodeCode						NVARCHAR(50) NULL
	, Federal_FinancialAccountCategoryCode								NVARCHAR(50) NULL
	, Federal_FinancialAccountProgramCodeCode							NVARCHAR(50) NULL
	, Federal_FinancialAccountFundClassificationCode					NVARCHAR(50) NULL
	, Sea_FinancialAccountCategoryCode									NVARCHAR(50) NULL
	, Sea_FinancialAccountCategoryDescription							NVARCHAR(150) NULL
	, Sea_FinancialAccountLocalProgramCodeCode							NVARCHAR(50) NULL
	, Sea_FinancialAccountLocalProgramCodeDescription					NVARCHAR(150) NULL
	, Sea_FinancialAccountLocalFundClassificationCode					NVARCHAR(50) NULL
	, Sea_FinancialAccountLocalFundClassificationDescription			NVARCHAR(150) NULL
	, Lea_FinancialAccountCategoryCode									NVARCHAR(50) NULL
	, Lea_FinancialAccountCategoryDescription							NVARCHAR(150) NULL
	, Lea_FinancialAccountLocalProgramCodeCode							NVARCHAR(50) NULL
	, Lea_FinancialAccountLocalProgramCodeDescription					NVARCHAR(150) NULL
	, Lea_FinancialAccountLocalFundClassificationCode					NVARCHAR(50) NULL
	, Lea_FinancialAccountLocalFundClassificationDescription			NVARCHAR(150) NULL
	, Federal_FinancialExpenditureFunctionCodeCode						NVARCHAR(50) NULL
	, Federal_FinancialExpenditureObjectCodeCode						NVARCHAR(50) NULL
	, Federal_FinancialExpenditureLevelOfInstructionCodeCode			NVARCHAR(50) NULL
	, Federal_FinancialExpenditureProjectReportingCodeCode				NVARCHAR(50) NULL
	, Sea_FinancialExpenditureLocalFunctionCodeCode						NVARCHAR(100) NULL
	, Sea_FinancialExpenditureLocalFunctionCodeDescription				NVARCHAR(300) NULL
	, Sea_FinancialExpenditureLocalObjectCodeCode						NVARCHAR(100) NULL
	, Sea_FinancialExpenditureLocalObjectCodeDescription				NVARCHAR(300) NULL
	, Sea_FinancialExpenditureLocalLevelOfInstructionCodeCode			NVARCHAR(100) NULL
	, Sea_FinancialExpenditureLocalLevelOfInstructionCodeDescription	NVARCHAR(300) NULL
	, Sea_FinancialExpenditureProjectReportingCodeCode					NVARCHAR(100) NULL
	, Sea_FinancialExpenditureProjectReportingCodeDescription			NVARCHAR(300) NULL
	, Lea_FinancialExpenditureLocalFunctionCodeCode						NVARCHAR(100) NULL
	, Lea_FinancialExpenditureLocalFunctionCodeDescription				NVARCHAR(300) NULL
	, Lea_FinancialExpenditureLocalObjectCodeCode						NVARCHAR(100) NULL
	, Lea_FinancialExpenditureLocalObjectCodeDescription				NVARCHAR(300) NULL
	, Lea_FinancialExpenditureLocalLevelOfInstructionCodeCode			NVARCHAR(100) NULL
	, Lea_FinancialExpenditureLocalLevelOfInstructionCodeDescription	NVARCHAR(300) NULL
	, Lea_FinancialExpenditureProjectReportingCodeCode					NVARCHAR(100) NULL
	, Lea_FinancialExpenditureProjectReportingCodeDescription			NVARCHAR(300) NULL
	, Federal_FinancialAccountRevenueCodeCode							NVARCHAR(50) NULL
	, Sea_FinancialAccountLocalRevenueCodeCode							NVARCHAR(50) NULL
	, Sea_FinancialAccountLocalRevenueCodeDescription					NVARCHAR(150) NULL
	, lea_FinancialAccountLocalRevenueCodeCode							NVARCHAR(50) NULL
	, lea_FinancialAccountLocalRevenueCodeDescription					NVARCHAR(150) NULL
	, Federal_FinancialAccountNumber									NVARCHAR(60) NULL
	, Federal_FinancialAccountName										NVARCHAR(200) NULL
	, Federal_FinancialAccountDescription								NVARCHAR(600) NULL
	, Sea_FinancialAccountNumber										NVARCHAR(60) NULL
	, Sea_FinancialAccountName											NVARCHAR(200) NULL
	, Sea_FinancialAccountDescription									NVARCHAR(600) NULL
	, Lea_FinancialAccountNumber										NVARCHAR(60) NULL
	, Lea_FinancialAccountName											NVARCHAR(200) NULL
	, Lea_FinancialAccountDescription									NVARCHAR(600) NULL
	, FederalProgramCode												NVARCHAR(50) NULL
	, FederalProgramCodeDescription							NVARCHAR(150) NULL
	, FederalProgramSubgrantCode										NVARCHAR(50) NULL
	, FederalProgramSubgrantCodeDescription						NVARCHAR(150) NULL
	, FinancialAccountingValue											DECIMAL(9,2) NOT NULL
	)