CREATE TABLE [Staging].[K12Organization] (
    [Id]                                                                   INT            IDENTITY (1, 1) NOT NULL,
    [IeuIdentifierSea]                                                     NVARCHAR (100) NULL,
    [IEU_OrganizationName]                                                 NVARCHAR (256) NULL,
    [IEU_OperationalStatusEffectiveDate]                                   DATETIME       NULL,
    [IEU_OrganizationOperationalStatus]                                    VARCHAR (100)  NULL,
    [IEU_WebSiteAddress]                                                   NVARCHAR (300) NULL,
    [IEU_RecordStartDateTime]                                              DATETIME       NULL,
    [IEU_RecordEndDateTime]                                                DATETIME       NULL,
    [LeaIdentifierSea]                                                     NVARCHAR (50)  NULL,
    [PriorLeaIdentifierSea]                                                NVARCHAR (50)  NULL,
    [LeaIdentifierNCES]                                                    NVARCHAR (50)  NULL,
    [LEA_SupervisoryUnionIdentificationNumber]                             VARCHAR (100)  NULL,
    [LeaOrganizationName]                                                  VARCHAR (256)  NULL,
    [LEA_WebSiteAddress]                                                   VARCHAR (300)  NULL,
    [LEA_OperationalStatus]                                                VARCHAR (100)  NULL,
    [LEA_OperationalStatusEffectiveDate]                                   DATETIME       NULL,
    [LEA_CharterLeaStatus]                                                 VARCHAR (100)  NULL,
    [LEA_CharterSchoolIndicator]                                           BIT            NULL,
    [LEA_Type]                                                             VARCHAR (100)  NULL,
    [LEA_McKinneyVentoSubgrantRecipient]                                   BIT            NULL,
    [LEA_GunFreeSchoolsActReportingStatus]                                 VARCHAR (100)  NULL,
    [LEA_TitleIinstructionalService]                                       VARCHAR (100)  NULL,
    [LEA_TitleIProgramType]                                                VARCHAR (100)  NULL,
    [LEA_K12LeaTitleISupportService]                                       VARCHAR (100)  NULL,
    [LEA_MepProjectType]                                                   VARCHAR (100)  NULL,
    [LEA_IsReportedFederally]                                              BIT            NULL,
    [LEA_RecordStartDateTime]                                              DATETIME       NULL,
    [LEA_RecordEndDateTime]                                                DATETIME       NULL,
    [SchoolIdentifierSea]                                                  NVARCHAR (50)  NULL,
    [PriorSchoolIdentifierSea]                                             NVARCHAR (50)  NULL,
    [School_PriorLeaIdentifierSea]                                         NVARCHAR (50)  NULL,
    [SchoolIdentifierNCES]                                                 NVARCHAR (50)  NULL,
    [SchoolOrganizationName]                                               VARCHAR (256)  NULL,
    [School_WebSiteAddress]                                                VARCHAR (300)  NULL,
    [School_OperationalStatus]                                             VARCHAR (100)  NULL,
    [School_OperationalStatusEffectiveDate]                                DATETIME       NULL,
    [School_Type]                                                          VARCHAR (100)  NULL,
    [School_MagnetOrSpecialProgramEmphasisSchool]                          VARCHAR (100)  NULL,
    [School_SharedTimeIndicator]                                           VARCHAR (100)  NULL,
    [School_VirtualSchoolStatus]                                           VARCHAR (100)  NULL,
    [School_NationalSchoolLunchProgramStatus]                              VARCHAR (100)  NULL,
    [School_ReconstitutedStatus]                                           VARCHAR (100)  NULL,
    [School_CharterSchoolIndicator]                                        BIT            NULL,
    [School_CharterSchoolOpenEnrollmentIndicator]                          BIT            NULL,
    [School_CharterSchoolFEIN]                                             VARCHAR (100)  NULL,
    [School_CharterSchoolFEIN_Update]                                      VARCHAR (100)  NULL,
    [School_CharterContractIDNumber]                                       VARCHAR (100)  NULL,
    [School_CharterContractApprovalDate]                                   DATETIME       NULL,
    [School_CharterContractRenewalDate]                                    DATETIME       NULL,
    [School_CharterPrimaryAuthorizer]                                      VARCHAR (100)  NULL,
    [School_CharterSecondaryAuthorizer]                                    VARCHAR (100)  NULL,
    [School_StatePovertyDesignation]                                       VARCHAR (100)  NULL,
    [School_SchoolImprovementAllocation]                                   MONEY          NULL,
    [School_IndicatorStatusType]                                           VARCHAR (100)  NULL,
    [School_GunFreeSchoolsActReportingStatus]                              VARCHAR (100)  NULL,
    [School_ProgressAchievingEnglishLanguageProficiencyIndicatorType]      VARCHAR (100)  NULL,
    [School_ProgressAchievingEnglishLanguageProficiencyStateDefinedStatus] VARCHAR (100)  NULL,
    [School_SchoolDangerousStatus]                                         VARCHAR (100)  NULL,
    [School_ComprehensiveAndTargetedSupport]                               VARCHAR (100)  NULL,
    [School_ComprehensiveSupport]                                          VARCHAR (100)  NULL,
    [School_TargetedSupport]                                               VARCHAR (100)  NULL,
    [School_ConsolidatedMigrantEducationProgramFundsStatus]                BIT            NULL,
    [School_MigrantEducationProgramProjectType]                            VARCHAR (100)  NULL,
    [School_TitleIPartASchoolDesignation]                                  VARCHAR (100)  NULL,
    [School_AdministrativeFundingControl]                                  NVARCHAR (100) NULL,
    [School_IsReportedFederally]                                           BIT            NULL,
    [School_RecordStartDateTime]                                           DATETIME       NULL,
    [School_RecordEndDateTime]                                             DATETIME       NULL,
    [SchoolYear]                                                           SMALLINT       NULL,
    [DataCollectionName]                                                   NVARCHAR (100) NULL,
    [NewIEU]                                                               BIT            NULL,
    [NewLEA]                                                               BIT            NULL,
    [NewSchool]                                                            BIT            NULL,
    [RunDateTime]                                                          DATETIME       NULL,
    CONSTRAINT [PK_K12Organization] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100, STATISTICS_NORECOMPUTE = ON, DATA_COMPRESSION = PAGE)
);


GO

