CREATE FUNCTION [RDS].[Get_Age](
      @birthDate DATETIME = NULL
	, @asOfDate DATETIME = NULL
) RETURNS INT

BEGIN
	RETURN 
		CASE 
			WHEN @birthDate IS NULL THEN -1
			WHEN (CONVERT(INT,CONVERT(char(8), ISNULL(@asOfDate, GETDATE()),112))-CONVERT(char(8), ISNULL(@birthDate, GETDATE()),112))/10000 <= 0 THEN -1
			ELSE CONVERT(VARCHAR(5), (CONVERT(INT,CONVERT(char(8), ISNULL(@asOfDate, GETDATE()),112))-CONVERT(char(8), ISNULL(@birthDate, GETDATE()),112))/10000)
		END 
END

GO

