CREATE TABLE [RDS].[FactAeStudentEnrollments] (
    [FactAeStudentEnrollmentId]           INT            IDENTITY (1, 1) NOT NULL,
    [AeProgramYearId]                     INT            NOT NULL,
    [DataCollectionId]                    INT            NOT NULL,
    [AeStudentId]                         BIGINT         NOT NULL,
    [AeProviderId]                        INT            NOT NULL,
    [AeProgramTypeId]                     INT            NOT NULL,
    [AeStudentStatusId]                   INT            NOT NULL,
    [ApplicationDateId]                   INT            NOT NULL,
    [EnrollmentEntryDateId]               INT            NOT NULL,
    [EnrollmentExitDateId]                INT            NOT NULL,
    [AePostsecondaryTransitionDateId]     INT            NOT NULL,
    [AeDemographicId]                     INT            NOT NULL,
    [K12DiplomaOrCredentialAwardDateId]   INT            NOT NULL,
    [K12AcademicAwardStatusId]            INT            NOT NULL,
    [QuarterlyEarningsAfterExitQ1]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ2]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ3]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ4]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ5]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ6]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ7]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ8]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ9]        DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ10]       DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ11]       DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ12]       DECIMAL (9, 2) NULL,
    [QuarterlyEarningsAfterExitQ13]       DECIMAL (9, 2) NULL,
    [InstructionalActivityHoursCompleted] DECIMAL (9, 2) NULL,
    [StudentCount]                        INT            NOT NULL,
    CONSTRAINT [PK_FactAeStudentEnrollments] PRIMARY KEY CLUSTERED ([FactAeStudentEnrollmentId] ASC),
    CONSTRAINT [FK_FactAeStudentEnrollments_AeDemographicId] FOREIGN KEY ([AeDemographicId]) REFERENCES [RDS].[DimAeDemographics] ([DimAeDemographicId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_AePostsecondaryTransitionDateId] FOREIGN KEY ([AePostsecondaryTransitionDateId]) REFERENCES [RDS].[DimDates] ([DimDateId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_AeProgramTypeId] FOREIGN KEY ([AeProgramTypeId]) REFERENCES [RDS].[DimAeProgramTypes] ([DimAeProgramTypeId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_AeProgramYearId] FOREIGN KEY ([AeProgramYearId]) REFERENCES [RDS].[DimAeProgramYears] ([DimAeProgramYearId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_AeProviderId] FOREIGN KEY ([AeProviderId]) REFERENCES [RDS].[DimAeProviders] ([DimAeProviderId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_AeStudentId] FOREIGN KEY ([AeStudentId]) REFERENCES [RDS].[DimPeople] ([DimPersonId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_AeStudentStatusId] FOREIGN KEY ([AeStudentStatusId]) REFERENCES [RDS].[DimAeStudentStatuses] ([DimAeStudentStatusId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_ApplicationDateId] FOREIGN KEY ([ApplicationDateId]) REFERENCES [RDS].[DimDates] ([DimDateId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_DataCollectionId] FOREIGN KEY ([DataCollectionId]) REFERENCES [RDS].[DimDataCollections] ([DimDataCollectionId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_EnrollmentEntryDateId] FOREIGN KEY ([EnrollmentEntryDateId]) REFERENCES [RDS].[DimDates] ([DimDateId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_EnrollmentExitDateId] FOREIGN KEY ([EnrollmentExitDateId]) REFERENCES [RDS].[DimDates] ([DimDateId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_K12AcademicAwardStatusId] FOREIGN KEY ([K12AcademicAwardStatusId]) REFERENCES [RDS].[DimK12AcademicAwardStatuses] ([DimK12AcademicAwardStatusId]),
    CONSTRAINT [FK_FactAeStudentEnrollments_K12DiplomaOrCredentialAwardDateId] FOREIGN KEY ([K12DiplomaOrCredentialAwardDateId]) REFERENCES [RDS].[DimDates] ([DimDateId])
);


GO

