CREATE TABLE [RDS].[ReportEDFactsOrganizationCounts] (
    [ReportEDFactsOrganizationCountId]            INT             IDENTITY (1, 1) NOT NULL,
    [CSSOEmail]                                   NVARCHAR (100)  NULL,
    [CSSOFirstName]                               NVARCHAR (100)  NULL,
    [CSSOLastOrSurname]                           NVARCHAR (100)  NULL,
    [CSSOTelephone]                               NVARCHAR (24)   NULL,
    [CSSOTitle]                                   NVARCHAR (100)  NULL,
    [Categories]                                  NVARCHAR (300)  NULL,
    [CategorySetCode]                             NVARCHAR (40)   NOT NULL,
    [CharterLeaStatus]                            NVARCHAR (100)  NULL,
    [CharterSchoolAuthorizerIdPrimary]            NVARCHAR (50)   NULL,
    [CharterSchoolAuthorizerIdSecondary]          NVARCHAR (50)   NULL,
    [CharterSchoolStatus]                         NVARCHAR (100)  NULL,
    [EffectiveDate]                               NVARCHAR (50)   NULL,
    [GRADELEVEL]                                  NVARCHAR (50)   NULL,
    [LEAType]                                     NVARCHAR (50)   NULL,
    [LEATypeId]                                   NVARCHAR (MAX)  NULL,
    [MAGNETSTATUS]                                NVARCHAR (MAX)  NULL,
    [MailingAddressCity]                          NVARCHAR (50)   NULL,
    [MailingAddressPostalCode]                    NVARCHAR (17)   NULL,
    [MailingAddressState]                         NVARCHAR (50)   NULL,
    [MailingAddressStreet]                        NVARCHAR (100)  NULL,
    [NSLPSTATUS]                                  NVARCHAR (MAX)  NULL,
    [OperationalStatus]                           NVARCHAR (50)   NULL,
    [OperationalStatusId]                         NVARCHAR (MAX)  NULL,
    [OrganizationCount]                           INT             NOT NULL,
    [OrganizationId]                              INT             NOT NULL,
    [OrganizationName]                            NVARCHAR (1000) NOT NULL,
    [OrganizationNcesId]                          NVARCHAR (100)  NULL,
    [OrganizationStateId]                         NVARCHAR (100)  NULL,
    [OutOfStateIndicator]                         NVARCHAR (MAX)  DEFAULT (N'0') NULL,
    [ParentOrganizationStateId]                   NVARCHAR (100)  NULL,
    [PhysicalAddressCity]                         NVARCHAR (50)   NULL,
    [PhysicalAddressPostalCode]                   NVARCHAR (17)   NULL,
    [PhysicalAddressState]                        NVARCHAR (50)   NULL,
    [PhysicalAddressStreet]                       NVARCHAR (100)  NULL,
    [PriorLeaStateIdentifier]                     NVARCHAR (50)   NULL,
    [PriorSchoolStateIdentifier]                  NVARCHAR (50)   NULL,
    [ReconstitutedStatus]                         NVARCHAR (100)  NULL,
    [ReportCode]                                  NVARCHAR (40)   NOT NULL,
    [ReportLevel]                                 NVARCHAR (40)   NOT NULL,
    [ReportYear]                                  NVARCHAR (40)   NOT NULL,
    [SHAREDTIMESTATUS]                            NVARCHAR (MAX)  NULL,
    [SchoolType]                                  NVARCHAR (50)   NULL,
    [SchoolTypeId]                                NVARCHAR (MAX)  NULL,
    [StateANSICode]                               NVARCHAR (100)  NOT NULL,
    [StateCode]                                   NVARCHAR (100)  NOT NULL,
    [StateName]                                   NVARCHAR (1000) NOT NULL,
    [SupervisoryUnionIdentificationNumber]        NCHAR (3)       NULL,
    [TITLE1SCHOOLSTATUS]                          NVARCHAR (MAX)  NULL,
    [TableTypeAbbrv]                              NVARCHAR (100)  NULL,
    [Telephone]                                   NVARCHAR (24)   NULL,
    [TotalIndicator]                              NVARCHAR (5)    NULL,
    [UpdatedOperationalStatus]                    NVARCHAR (50)   NULL,
    [UpdatedOperationalStatusId]                  NVARCHAR (MAX)  NULL,
    [VIRTUALSCHSTATUS]                            NVARCHAR (MAX)  NULL,
    [Website]                                     NVARCHAR (100)  NULL,
    [TitleiParentalInvolveRes]                    INT             DEFAULT ((0)) NOT NULL,
    [TitleiPartaAllocations]                      INT             DEFAULT ((0)) NOT NULL,
    [ParentOrganizationNcesId]                    NVARCHAR (100)  NULL,
    [CharterSchoolIndicator]                      BIT             NULL,
    [CharterSchoolContractIdNumber]               NVARCHAR (MAX)  NULL,
    [CharterContractApprovalDate]                 NVARCHAR (MAX)  NULL,
    [CharterContractRenewalDate]                  NVARCHAR (MAX)  NULL,
    [LeaNcesIdentifier]                           NVARCHAR (MAX)  NULL,
    [LeaStateIdentifier]                          NVARCHAR (MAX)  NULL,
    [ManagementOrganizationType]                  NVARCHAR (MAX)  NULL,
    [IMPROVEMENTSTATUS]                           NVARCHAR (MAX)  NULL,
    [PERSISTENTLYDANGEROUSSTATUS]                 NVARCHAR (MAX)  NULL,
    [CHARTERSCHOOLMANAGERORGANIZATION]            NVARCHAR (MAX)  NULL,
    [CHARTERSCHOOLUPDATEDMANAGERORGANIZATION]     NVARCHAR (MAX)  NULL,
    [STATEPOVERTYDESIGNATION]                     NVARCHAR (50)   NULL,
    [SCHOOLIMPROVEMENTFUNDS]                      INT             NULL,
    [EconomicallyDisadvantagedStudentCount]       INT             NULL,
    [McKinneyVentoSubgrantRecipient]              VARCHAR (50)    NULL,
    [ProgressAchievingEnglishLanguage]            NVARCHAR (MAX)  NULL,
    [StateDefinedStatus]                          NVARCHAR (MAX)  NULL,
    [REAPAlternativeFundingStatus]                NVARCHAR (50)   NULL,
    [GraduationRate]                              NVARCHAR (50)   NULL,
    [GunFreeStatus]                               NVARCHAR (50)   NULL,
    [FederalFundAllocationType]                   NVARCHAR (20)   NULL,
    [FederalProgramCode]                          NVARCHAR (20)   NULL,
    [FederalFundAllocated]                        INT             NULL,
    [ComprehensiveAndTargetedSupportCode]         NVARCHAR (50)   NULL,
    [ComprehensiveSupportCode]                    NVARCHAR (50)   NULL,
    [TargetedSupportCode]                         NVARCHAR (50)   NULL,
    [ComprehensiveSupportImprovementCode]         NVARCHAR (50)   NULL,
    [TargetedSupportImprovementCode]              NVARCHAR (50)   NULL,
    [AdditionalTargetedSupportandImprovementCode] NVARCHAR (50)   NULL,
    [AppropriationMethodCode]                     NVARCHAR (50)   NULL,
    CONSTRAINT [PK_ReportEDFactsOrganizationCounts] PRIMARY KEY CLUSTERED ([ReportEDFactsOrganizationCountId] ASC) WITH (FILLFACTOR = 80, DATA_COMPRESSION = PAGE)
);


GO

CREATE NONCLUSTERED INDEX [IX_ReportEDFactsOrganizationCounts_ReportCode_ReportYear_ReportLevel_Grade_Organization]
    ON [RDS].[ReportEDFactsOrganizationCounts]([ReportCode] ASC, [ReportYear] ASC, [ReportLevel] ASC)
    INCLUDE([GRADELEVEL], [OrganizationId]) WITH (FILLFACTOR = 80, DATA_COMPRESSION = PAGE);


GO

CREATE NONCLUSTERED INDEX [IX_ReportEDFactsOrganizationCounts_ReportCode_ReportYear_ReportLevel_CategorySetCode]
    ON [RDS].[ReportEDFactsOrganizationCounts]([ReportCode] ASC, [ReportYear] ASC, [ReportLevel] ASC, [CategorySetCode] ASC) WITH (FILLFACTOR = 80, DATA_COMPRESSION = PAGE);


GO

