CREATE TABLE [CEDS].[CodeSet](
	[CodeSetID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](100) NOT NULL,
	[HtmlColumns] [int] NOT NULL,
	[GeneratedHtml] [varchar](max) NULL,
	[GeneratedExcel] [varchar](max) NULL,
 CONSTRAINT [PK_CodeSet] PRIMARY KEY CLUSTERED 
(
	[CodeSetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [CEDS].[CodeSet] ADD  CONSTRAINT [DF_CodeSet_HtmlColumns]  DEFAULT ((1)) FOR [HtmlColumns]
GO


