ALTER TABLE [RDS].[DimFederalFinancialExpenditureClassifications]
DROP COLUMN FinancialExpenditureProjectReportingCodeCode

ALTER TABLE [RDS].[DimFederalFinancialExpenditureClassifications]
DROP COLUMN FinancialExpenditureProjectReportingCodeDescription